config/routes.rb
Gastos::Application.routes.draw do
  resources :users

  resources :gastos

  resources :clientes
	
	get 'logout', to: 'sessions#logout', :as => :logout
	   
	resources :sessions

  root 'gastos#index'

end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
	belongs_to :cliente

	def self.mios(user_id)
		where(:user_id => user_id)
	end

	def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |product|
      csv << product.attributes.values_at(*column_names)
    end
  end
end
end

app/controllers/gastos_controller.rb
class GastosController < ApplicationController
  before_action :set_gasto, only: [:show, :edit, :update, :destroy]

  # GET /gastos
  # GET /gastos.json
  def index
 		@gasto = Gasto.new
    @gasto.fecha = Date.today
		unless params[:desde] && params[:hasta]
			hoy = Date.today()
			@desde = Date.new(hoy.year,hoy.month,1)
			@hasta = Date.new(hoy.year,hoy.month,-1)
		else
			@desde = params[:desde].to_date
			@hasta = params[:hasta].to_date
		end
			@totalCliente = Gasto.mios(@current_user.id).where("fecha >= '#{@desde}' and fecha <=  '#{@hasta}'").group(:cliente_id).sum('COALESCE(ingreso, 0)- COALESCE(egreso, 0)')
			@gastos = Gasto.mios(@current_user.id).where("fecha >= '#{@desde}' and fecha <=  '#{@hasta}'").order(:fecha)
			@saldoInicial = Gasto.mios(@current_user.id).where("fecha < '#{@desde}'").sum('COALESCE(ingreso, 0)- COALESCE(egreso, 0)').to_f rescue nil
	 if Gasto.last.nil?
      @ultimo_cliente = Cliente.last.id
    else
      @ultimo_cliente = Gasto.last.cliente.id
    end
    @clientes = Cliente.xUltimoUso(session[:user_id])
  end
  respond_to do |format|
    format.html
    format.xls {send_data @gastos.to_csv}
  end
  # GET /gastos/1
  # GET /gastos/1.json
  def show
  end

  # GET /gastos/new
  def new
    @gasto = Gasto.new
    @gasto.fecha = Date.today
	end

  # GET /gastos/1/edit
	def edit
		@gasto = Gasto.find(params[:id])
    @clientes = Cliente.xUltimoUso(session[:user_id])

		respond_to do |format|	
			format.js
		end
	end

	# POST /gastos
	# POST /gastos.json
  def create
    @gasto = Gasto.new(gasto_params)
		@gasto.user_id = @current_user.id
    respond_to do |format|
      if @gasto.save
        format.html { redirect_to :back }
        format.json { render action: 'show', status: :created, location: @gasto }
      else
        format.html { render action: 'new' }
        format.json { render json: @gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gastos/1
  # PATCH/PUT /gastos/1.json
  def update
    respond_to do |format|
      if @gasto.update(gasto_params)
        format.html { redirect_to :back }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gastos/1
  # DELETE /gastos/1.json
  def destroy
    @gasto.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gasto
      @gasto = Gasto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gasto_params
      params.require(:gasto).permit(:fecha, :concepto, :ingreso, :egreso, :cliente_id, :user_id)
    end
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/views/gastos/_form.html.erb
<%= hidden_field_tag 'esForm', 'true' %>

<%= form_for(@gasto) do |f| %>
  <% if @gasto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gasto.errors.count, "error") %> prohibited this gasto from being saved:</h2>

      <ul>
      <% @gasto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
		<input type="date" id="fecha" name="gasto[fecha]" tabindex="1" value="<%= @gasto.fecha%>" autocomplete="on" /></p>
  </div>
  <div class="field">
    <%= f.label :concepto %><br>
		<%= f.text_area :concepto, :tabindex =>2, :style=> 'width:400px' %>
  </div>
  <div class="field">
    <%= f.label :ingreso %><br>
    <%= f.text_field :ingreso, :tabindex =>3 %>
  </div>
  <div class="field">
    <%= f.label :egreso %><br>
    <%= f.text_field :egreso, :tabindex =>4 %>
  </div>
  <div class="field">
		<%= f.label :cliente_id %><br>
		<% unless @gasto.id %>
		<%= f.collection_select(:cliente_id, @clientes, :id, :nombre, {:selected => @ultimo_cliente}, {:tabindex =>5}) %>
	<%else%>
		<%= f.collection_select(:cliente_id, @clientes, :id, :nombre, {}, {:tabindex =>5}) %>
		<%end%>
	
	</div>
  <div class="actions">
    <%= f.submit "CREAR", id: "crear", :tabindex => 6 %>
  </div>
<% end %>

app/views/gastos/edit.html.erb
<h1>Editing gasto</h1>

<%= render 'form' %>

<%= link_to 'Show', @gasto %> |
<%= link_to 'Back', gastos_path %>

app/views/gastos/edit.js.erb
$('#edit').html("<%=j render 'form' %>").css('display','block');
$('#overlay').addClass('overlay');
$('#edit #fecha').focus();
$.fn.initChosen();
jQuery.fn.activarCalcular();

app/views/gastos/index.html.erb
<input id="action" type="hidden" value="<%= action_name %>">
<h1>Rendición de gastos <%=@current_user.nombre%>
	<%unless !@desde || !@hasta %>
		<%= "[ "+ @desde.strftime("%d/%m/%Y") + " → " + @hasta.strftime("%d/%m/%Y") + " ]"  %>
	<%else%>
		<%= "[TODOS LOS REGISTROS]"  %>
<%end %>
</h1>
<div id="filtro" class="modal">
	<form method="get" action=<%= gastos_path %> >
		DESDE: <input type="date" name="desde" value=<%=@desde%> /><br>
		HASTA: <input type="date" name="hasta" value=<%=@hasta %> /><br>
	<input type="submit" value="Filtrar" style="align:center">
</form>
</div>
<div class="CSSTableGenerator">
<table>
    <tr>
      <td>Fecha</td>
      <td>Concepto</td>
      <td>Ingreso</td>
      <td>Egreso</td>
      <td>Saldo</td>
      <td>Cliente</td>
      <td class="noPrint"></td>
      <td class="noPrint"></td>
    </tr>

	<% if @saldoInicial != 0 %>
		<tr>
			<td> <%= @desde.strftime("%d/%m/%Y") %> </td>
			<td colspan="3">SALDO INICIAL AL <%= @desde %></td>
			<td><%= @saldoInicial %></td>
			<td colspan="3"></td>	
		
		</tr>
    <% end %>
	<% saldo = 0 + @saldoInicial %>
	<% @gastos.each do |gasto| %>
      <tr>
        <td><%= gasto.fecha.strftime("%d/%m/%Y") %></td>
        <td><%= gasto.concepto.upcase.html_safe %></td>
        <td><%= gasto.ingreso %></td>
        <td><%= gasto.egreso %></td>
				<td><%= saldo = saldo + gasto.ingreso.to_f - gasto.egreso.to_f %></td>

        <td><%= gasto.cliente.nombre %></td>

				<td class="noPrint"><%= link_to 'Editar', edit_gasto_path(gasto), :remote => true %></td>
        <td class="noPrint"><%= link_to 'Borrar', gasto, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
</table>
<br>
<br>
<table>
    <tr>
      <td>Cliente</td>
      <td>Total</td>
    </tr>

	<% @totalCliente.each do |k,v| %>
		<tr>
			<td><%= Cliente.find(k).nombre %> </td>
			<td><%= v.to_f %></td>
		</tr>	
<% end %>
</table>
</div>
<br>
<div id="nuevo" class="modal_form">
<%= render 'form' %>
</div>

<div id="edit" class="modal_form">
</div>

<%= link_to 'Nuevo(Ctrl + Shift + a)', '#' ,:class=>"noPrint", :id => "crearNuevo", :remote=>true %>
&nbsp
<%= link_to 'Filtros(Ctrl + Shift + f)', '#' ,:class=>"noPrint", :id => "abrirFiltro", :remote=>true %>
&nbsp
<%= link_to 'Nuevo Cliente', new_cliente_path(:desde => @desde, :hasta => @hasta) ,:class=>"noPrint"%>
&nbsp
<%= link_to 'Mi usuario', edit_user_path(@current_user.id) ,:class=>"noPrint"%>
&nbsp
<%= link_to 'XLS', gastos_path(format: "xls", :desde => @desde, :hasta => @hasta), :class=>"noPrint", :id => "XLS" %>
<%= link_to 'Salir', logout_path ,:class=>"noPrint"%>
&nbsp

app/views/gastos/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
      <% saldo = 0 + @saldoInicial %>
        <Cell><Data ss:Type="String">Fecha</Data></Cell>
        <Cell><Data ss:Type="String">Concepto</Data></Cell>
        <Cell><Data ss:Type="String">Ingreso</Data></Cell>
        <Cell><Data ss:Type="String">Egreso</Data></Cell> 
        <Cell><Data ss:Type="String">Saldo</Data></Cell>
      </Row>
    <% @gastos.each do |gasto| %>
      <Row>
        <Cell><Data ss:Type="Date"><%= gasto.fecha.strftime("%d/%m/%Y") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= gasto.concepto %></Data></Cell>
        <Cell><Data ss:Type="String"><%= gasto.ingreso %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= gasto.egreso %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= saldo = saldo + gasto.ingreso.to_f - gasto.egreso.to_f %> %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/gastos/new.html.erb
<h1>New gasto</h1>

<%= render 'form' %>

<%= link_to 'Back', gastos_path %>

app/views/gastos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @gasto.fecha %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @gasto.concepto %>
</p>

<p>
  <strong>Ingreso:</strong>
  <%= @gasto.ingreso %>
</p>

<p>
  <strong>Egreso:</strong>
  <%= @gasto.egreso %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @gasto.cliente.nombre %>
</p>

<%= link_to 'Edit', edit_gasto_path(@gasto) %> |
<%= link_to 'Back', gastos_path %>